organ: "MyOrganization"
organ_domain: "com.myorganization"
name: "NewQtProject"
ver: "0.1.0"
author: "AuthorName"
email: "contact_email@example.com"
copyright: "Copyright (c) 2026 AuthorName"  # 可留空，将自动根据年份和作者名生成
cppver: 17
appicon: "/path/to/icon.png"
